version: 2

references:
  attach_workspace: &attach_workspace
    attach_workspace:
      at: /tmp/workspace

jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go test -v ./... -mod vendor

  release-controller:
    machine: true
    steps:
      - checkout
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run: ./scripts/ci/release-controller

  release-agent:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: curl -fsSL https://get.docker.com/ -o docker-install.sh
      - run: sh docker-install.sh
      - run: |-
          mkdir -p ~/.docker && echo '{"experimental":"enabled"}' > ~/.docker/config.json
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run: ./scripts/ci/release-agent

  release-cli:
    machine: true
    steps:
      - checkout
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run: ./scripts/ci/release-cli

  build-cli-binaries:
    docker:
      - image: circleci/golang:1.13
    steps:
      - *attach_workspace
      - checkout
      - run: ./scripts/ci/build-cli-binaries
      - run: mv dist /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist

  upload-cli-binaries:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - *attach_workspace
      - checkout
      - run: ./scripts/ci/upload-cli-binaries

  upload-cli-binary-redirects:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run: ./scripts/ci/upload-cli-binary-redirects

workflows:
  version: 2
  test_release:
    jobs:
      - test
      - release-controller:
          requires:
            - test
          filters:
            branches:
              only: master
      - release-agent:
          requires:
            - test
          filters:
            branches:
              only: master
      - release-cli:
          requires:
            - test
          filters:
            branches:
              only: master
      - build-cli-binaries:
          requires:
            - test
          filters:
            branches:
              only: master
      - upload-cli-binaries:
          requires:
            - build-cli-binaries
          filters:
            branches:
              only: master
      - upload-cli-binary-redirects:
          requires:
            - upload-cli-binaries
          filters:
            branches:
              only: master
